Platon/backend/app/auth_system/helpers.py, Platon/backend/app/follow_system/views.py, Platon/backend/app/profile_management/forms.py, Platon/backend/app/profile_management/helpers.py, Platon/backend/app/profile_management/models.py, Platon/backend/app/profile_management/views.py, Platon/backend/config.py, Platon/backend/test.py, Platon/backend/tests/auth_system_test.py, Platon/backend/tests/profile_management_test.py
I implemented tests and notification system. Also I added to the places where we will send notification to the user in the Follow System. @cakmadam98 Please review these parts before merging the code. All tests are passed.
=> Notification System is Finished

Platon/backend/app/follow_system/views.py
GET methods of Followings, Followers and FollowRequests now return more information about User rather than only user_id.
=> Follow System update

Platon/docker-compose.yml
To have persistent data in our database container, I've changed the Composefile as suggested on the internet. It worked on my own computer. I hope it will solve our problem on our server too. Could you please try and let me know? @HUmutOzdemir
=> Add persistent data volume to database container

Platon/backend/app/auth_system/views.py, Platon/backend/app/follow_system/forms.py, Platon/backend/app/follow_system/views.py, Platon/backend/app/profile_management/models.py, Platon/backend/app/profile_management/views.py, Platon/backend/tests/follow_test.py
- API documentation is added for Authentication, Follow and Profile Management systems.
- Unfollow mechanism is added with its unit tests.
- All follow system unit tests are updated and they are successfully passed.
=> Backend dev follow m2

Platon/backend/app/profile_management/forms.py, Platon/backend/app/profile_management/views.py
I added agination to Research Information and Notification Get Requests
=> Pagination is added

Platon/backend/app/follow_system/forms.py
=> Replace args with form in documentation

Platon/backend/app/follow_system/forms.py, Platon/backend/app/follow_system/views.py, Platon/backend/tests/follow_test.py
This PR solves the latest problems happened in GET methods of Follow System. Unit tests, forms and views are changed.
=> Follow System Request-Response Cycle is updated

Platon/backend/app/follow_system/forms.py, Platon/backend/app/follow_system/views.py
Unit tests are passed since it is backwards compatible. Also I've corrected a small typo in the FollowRequest documentation.
=> Follow System Pagination added

Platon/backend/app/__init__.py, Platon/backend/app/auth_system/forms.py, Platon/backend/app/auth_system/helpers.py, Platon/backend/app/auth_system/views.py, Platon/backend/app/follow_system/helpers.py, Platon/backend/config.py, Platon/backend/tests/base_test.py, Platon/docker-compose.yml
I added the profile photo upload functionality and also solved the issue about private accounts. Please review my code.
=> Backend dev profile photo

Platon/backend/app/__init__.py, Platon/backend/app/workspace_system/forms.py, Platon/backend/app/workspace_system/models.py
You can find the models for the Workspace system in the code here. I kindly ask you to review the code.
=> Backend dev workspaces

Platon/backend/app/follow_system/helpers.py
Solves the problem stated in #256 . Didn't implement an unit test for it. I've tested it manually by using AWS DB.
=> Update Follow System Helper

Platon/backend/app/search_engine/forms.py, Platon/backend/app/search_engine/views.py
A BAsic Semantic Search is implemented for Workspaces. Please review this code.
=> Workspace Basic Search is implemented

Platon/frontend/src/components/Workspace/WorkspaceEdit/WorkspaceEdit.js, Platon/frontend/src/components/Workspace/WorkspaceInput/WorkspaceInputOptional/WorkspaceInputOptional.js, Platon/frontend/src/components/Workspace/WorkspaceInput/WorkspaceInputSkill/WorkspaceInputSkill.js, Platon/frontend/src/components/Workspace/WorkspaceInput/WorkspaceInputState/WorkspaceInputState.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceView.js
Edit workspace feature is not connected fully yet
=> Frontend dev workspace

Platon/frontend/src/components/HomePage/HomePage.jsx, Platon/frontend/src/components/NavBar/NavBar.js
I created a delete feature for notification, I made a new section for notifications and paginated there, also I renewed the navbar, therefore the sider is no longer needed.
=> Frontend dev notification

Platon/frontend/src/components/NavBar/NavBar.js, Platon/frontend/src/components/Workspace/WorkspaceInput/WorkspaceInputOptional/WorkspaceInputOptional.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceView.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSection.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSectionEditConfirmation/WorkspaceViewFileSectionEditConfirmation.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSectionPreviewConfirmation/WorkspaceViewFileSectionPreviewConfirmation.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewStateTimeline/WorkspaceViewStateTimeline.js
The workspace details page is styled, the file system page is styled, file preview feature is added.
=> File preview feature is added 

Platon/backend/app/workspace_system/views.py, Platon/backend/tests/issues_test.py
This improvement was requested from frontend. Unit test is written and passed.
=> Post Issue Now Returns Issue ID

Platon/backend/Dockerfile, Platon/backend/app/workspace_system/views.py, Platon/backend/tests/issues_test.py
new unit tests are written and passed.
=> Backend Dev Post Issue Improvement

Platon/backend/app/file_system/views.py, Platon/backend/app/profile_management/views.py
There are 2 issues that state the bugs of the endpoints that I implemented.
1. In the `folder` endpoint of the file system, there is a bug on the `cwd` filed of the response. I solved the bug in this PR.
2. In the `notifications` endpoint, there is a problem with the order of the notifications. I solved this bug in this PR.
Please review my code.
=> Backend dev bug fixes

Platon/frontend/src/components/NavBar/NavBar.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceView.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSection.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSectionEditConfirmation/WorkspaceViewFileSectionEditConfirmation.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSectionPreviewConfirmation/WorkspaceViewFileSectionPreviewConfirmation.js
Notification and file preview bugs are fixed, also some bugs caused by file preview are also fixed
=> Notification and file preview bugs are fixed

Platon/backend/app/search_engine/forms.py, Platon/backend/app/search_engine/views.py, Platon/backend/test.py, Platon/backend/tests/search_engine_test.py
Customer requirements are covered. Input and output formats are updated as customer requests. Filtering and sorting functionality are added. Unit tests are written and all unit tests are passed.
=> Backend Dev Workspace Search Completed

Platon/backend/app/workspace_system/forms.py, Platon/backend/app/workspace_system/helpers.py, Platon/backend/app/workspace_system/models.py, Platon/backend/app/workspace_system/views.py
I've created the mechanism for adding/reading/removing upcoming events for workspaces into the Workspaces API, I kindly ask your code review.
=> Insert the mechanism for adding/reading/removing upcoming events for workspaces into the Workspaces API

Platon/frontend/src/components/EditProfile/EditProfile.css, Platon/frontend/src/components/ProfilePage/ProfilePage.js, Platon/frontend/src/components/Search/Search.js
Invitation is added, some bugs are fixed.
=> Invitation and Small Changes after Merge

Platon/backend/app/workspace_system/views.py
Issue and Issue Comment now returns user's profile photo information.
=> GET Issue & Issue Comment - Profile Photo Information

Platon/frontend/src/components/HomePage/Comment.js, Platon/frontend/src/components/HomePage/InfiniteScroll.js, Platon/frontend/src/components/HomePage/commentStyle.css
#394 pull request's merge conflicts caused style loss on the home page. I provided the necessary changes
=> Home page merge conflict issue is solved

Platon/frontend/src/components/Workspace/WorkspaceList/WorkspaceList.js
=> Incoming invitations

Platon/frontend/src/components/Search/Search.css, Platon/frontend/src/components/Search/Search.js, Platon/frontend/src/services/requestService.js
Search mechanism is added with users, workspaces, and upcoming events.
=> Search Mechanism

Platon/app/src/main/java/com/cmpe451/platon/adapter/IssueCommentAdapter.kt, Platon/app/src/main/java/com/cmpe451/platon/network/Webservice.kt, Platon/app/src/main/java/com/cmpe451/platon/network/models/Issue.kt, Platon/app/src/main/java/com/cmpe451/platon/page/activity/workspace/fragment/issuedetail/IssueDetailFragment.kt, Platon/app/src/main/java/com/cmpe451/platon/page/activity/workspace/fragment/issuedetail/IssueDetailRepository.kt, Platon/app/src/main/java/com/cmpe451/platon/page/activity/workspace/fragment/issuedetail/IssueDetailViewModel.kt, Platon/app/src/main/res/drawable/ic_delete_dark_24dp.xml, Platon/app/src/main/res/layout/dialog_issue_add_comment.xml, Platon/app/src/main/res/layout/fragment_issue_detail.xml, Platon/app/src/main/res/layout/issue_comment_cell.xml, Platon/app/src/main/res/values/strings.xml
=> Android release issue comment

Platon/frontend/src/components/Workspace/WorkspaceCreate/WorkspaceCreate.js, Platon/frontend/src/components/Workspace/WorkspaceEdit/WorkspaceEdit.js, Platon/frontend/src/components/Workspace/WorkspaceInput/WorkspaceInputDate/WorkspaceInputDate.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceView.js
Attaching Upcoming Events to the workspace is added.
=> Frontend Attaching Upcoming Events 

Platon/backend/app/search_engine/forms.py, Platon/backend/app/search_engine/views.py
Tag search functionality is implemented
=> Tag Search is implemented

Platon/backend/app/__init__.py, Platon/backend/app/auth_system/views.py, Platon/backend/app/profile_management/helpers.py, Platon/backend/config.py, Platon/backend/templates/account_verification.html, Platon/backend/templates/reset_password.html
E-mail HTML Templates are added
=> Backend dev notification

Platon/backend/app/workspace_system/views.py
Now (possible) private informations of the users are not returned. Solves the issue #373
=> IssueAPI and MilestoneAPI Privacy Improvement

Platon/backend/app/workspace_system/forms.py, Platon/backend/app/workspace_system/views.py, Platon/backend/tests/issues_test.py
this PR adds functionalities that will solve the issue #408
=> IssueInfoAPI implemented

Platon/frontend/src/components/ProfilePage/ProfilePage.js, Platon/frontend/src/components/UpcomingEvents/UpcomingEventsItem/UpcomingEventsItem.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSectionPreviewConfirmation/WorkspaceViewFileSectionPreviewConfirmation.js
Images in the file section can be previewed from now on.
=> Frontend - Implementation of image preview in file section

Platon/backend/app/recommendation_system/helpers.py
Published State Workspaces are removed from Recommendations as stated in Issue #444. Also, the frequency of the background process is decreased.
=> Published State Workspaces are removed from Recommendations #444

Platon/backend/app/activity_stream/views.py, Platon/backend/app/recommendation_system/helpers.py, Platon/backend/tests/activity_stream_test.py
contains improvement for Activity Stream
=> Backend dev to Release

Platon/frontend/src/components/NotFound/__test__/NotFound.test.js, Platon/frontend/src/components/Recommendation/CollaboratorRecommendation/CollaboratorRecommendationDialog/__test__/CollaboratorRecommendationDialog.test.js, Platon/frontend/src/components/Recommendation/WorkspaceRecommendation/__test__/WorkspaceRecommendation.test.js, Platon/frontend/src/components/Spinner/__test__/Spinner.test.js
Unit tests are added for the components implemented for Milestone 3
=> Unit tests are added 

Platon/.idea/assetWizardSettings.xml, Platon/app/src/main/java/com/cmpe451/platon/network/Webservice.kt, Platon/app/src/main/java/com/cmpe451/platon/page/activity/home/fragment/otherprofile/OtherProfileFragment.kt, Platon/app/src/main/java/com/cmpe451/platon/page/activity/home/fragment/otherprofile/OtherProfileRepository.kt, Platon/app/src/main/java/com/cmpe451/platon/page/activity/home/fragment/otherprofile/OtherProfileViewModel.kt, Platon/app/src/main/res/drawable/ic_report_24px.xml, Platon/app/src/main/res/layout/dialog_add_comment.xml, Platon/app/src/main/res/layout/dialog_report_user.xml, Platon/app/src/main/res/layout/fragment_profile_page_others.xml, Platon/app/src/main/res/values/strings.xml
Please validate my implementation of new reporting feature. You can track [issue](https://github.com/bounswe/bounswe2020group7/issues/458) from here
=> Reporting User feature into Android-Dev

Platon/frontend/src/components/NavBar/NavBar.js
Navbar was routing wrong after trying to reach the profile from another one's profile. It is fixed.
=> Navbar router bug is fixed

Platon/frontend/src/components/NavBar/NavBar.js
Missing href argument that causing not routing to the homepage is added.
=> BUG FIX - Missing href argument is added.

Platon/frontend/src/components/HomePage/Comment.js, Platon/frontend/src/components/HomePage/HomePage.jsx, Platon/frontend/src/components/HomePage/InfiniteScroll.js
=> Activity stream is styled

Platon/frontend/src/components/HomePage/Comment.js
Empty clickable area is removed by changing div to span
=> Empty clickable area is removed by changing div to span

Platon/backend/app/upcoming_events/forms.py, Platon/backend/app/upcoming_events/views.py
I've written the endpoint for the personal calendar. I've tested it with several states of the database, it works fine so far. I kindly ask you to review my code.
=> Create the personal calendar endpoint

Platon/frontend/src/components/HomePage/HomePage.jsx, Platon/frontend/src/components/HomePage/InfiniteScroll.js, Platon/frontend/src/components/TrendingProjects/TrendingProjects.js, Platon/frontend/src/components/UpcomingEvents/UpcomingEvents.css, Platon/frontend/src/components/UpcomingEvents/UpcomingEvents.js
=> Homepage is styled

Platon/app/src/main/java/com/cmpe451/platon/adapter/IssueCommentAdapter.kt, Platon/app/src/main/java/com/cmpe451/platon/network/Webservice.kt, Platon/app/src/main/java/com/cmpe451/platon/page/activity/workspace/fragment/issuedetail/IssueDetailFragment.kt, Platon/app/src/main/java/com/cmpe451/platon/page/activity/workspace/fragment/issuedetail/IssueDetailRepository.kt, Platon/app/src/main/res/layout/issue_comment_cell.xml
=> Delete issue comment added.

Platon/backend/app/activity_stream/helpers.py, Platon/backend/app/file_system/views.py, Platon/backend/app/workspace_system/views.py
Please review our new changes @cakmadam98.
=> Backend Activity Stream Improvement

Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewTagSearch/WorkspaceViewTagSearch.js
BUG FIX - A UI bug is fixed resulting from 0 valued response result.
=> BUG FIX - A UI bug is fixed resulting from 0 valued response result.

Platon/frontend/src/components/Deadlines/Deadlines.css, Platon/frontend/src/components/Deadlines/Deadlines.js, Platon/frontend/src/components/Deadlines/DeadlinesItem/DeadlinesItem.js, Platon/frontend/src/components/HomePage/HomePage.jsx, Platon/frontend/src/components/TrendingProjects/TrendingProjects.js, Platon/frontend/src/components/Workspace/WorkspaceList/WorkspaceList.js
Added deadlines list widget on workspaces page as a calendar alternative.
- Go to workspaces page
**Expected:** Deadlines list widget should be visible on right side of the screen
- Click on a deadline
**Expected:** You are redirected to related workspace page
=> Add: Deadlines list widget on workspaces page (calendar alternative)

Platon/frontend/src/components/AppBar/AppBar.js, Platon/frontend/src/components/NavBar/NavBar.js, Platon/frontend/src/components/Search/Search.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSection.js, Platon/frontend/src/components/Workspace/WorkspaceView/WorkspaceViewFileSection/WorkspaceViewFileSectionRenameConfirmation/WorkspaceViewFileSectionRenameConfirmation.js
File rename and empty search bugs are fixed
=> File rename and empty search bugs are fixed
